---
title: Kyru Cabading | Front-end Developer
author: Kyru Cabading
email: kyrusri@gmail.com
description: ''
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
